insults = [
    "You're as bright as a black hole, and twice as dense.",
    "Your secrets are safe with me. I never even listen when you tell me them.",
    "You're proof that even evolution takes a wrong turn sometimes.",
    "You bring everyone so much joy… when you leave the room.",
    "You have something on your chin… no, the third one down.",
    "You have something on your face—oh wait, that’s just your personality.",
    "You’re not stupid; you just have bad luck thinking.",
    "You're like a software update—whenever I see you, I think, 'Do I really need this right now?'",
    "You bring people closer… to the exits.",
    "Your secrets are safe with me. I never even listen when you tell me them.",
    "You're about as useful as a screen door on a submarine.",
    "You're proof that even evolution takes a wrong turn sometimes.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You're the reason they put directions on shampoo bottles.",
    "You have something on your face—oh wait, that's just your personality.",
    "You're as sharp as a marble.",
    "You're like a penny—two-faced and not worth much.",
    "You have something on your chin… no, the third one down.",
    "You're not completely useless. You can always serve as a bad example.",
    "You're like a candle in the wind—burning out quickly and mostly unnoticed.",
    "You're about as useful as a chocolate teapot.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You're proof that even evolution takes a wrong turn sometimes.",
    "You're like a software update—whenever I see you, I think, 'Do I really need this right now?'",
    "You're as necessary as a fish needs a bicycle.",
    "You're living proof that even mistakes can have a purpose.",
    "You're slower than a snail on a treadmill.",
    "You're so dense, light bends around you.",
    "You're like a broken pencil—pointless.",
    "You're about as useful as a solar-powered flashlight.",
    "You're like a black hole—no light, no hope, just endless sucking.",
    "You're so slow, even a sloth would give you a side-eye.",
    "You're the reason why warning labels exist.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You're like a phone without WiFi—completely useless.",
    "You're as pleasant as stepping on a LEGO.",
    "You're as welcome as a pop-up ad on a slow internet connection.",
    "You're the human equivalent of a 404 error.",
    "You're like a speed bump on the road of life—just slowing everyone down.",
    "You're about as useful as a screen door on a submarine.",
    "You're like a radio station with bad reception—just noise and static.",
    "You're as useless as a white crayon.",
    "You're like an expired coupon—no value to anyone.",
    "You're proof that some people should come with a mute button.",
    "You're as enjoyable as buffering during a video.",
    "You're the dictionary definition of 'why though?'",
    "You're like an elevator that doesn't go to the top floor.",
    "You're as confusing as an IKEA instruction manual.",
    "You're as helpful as an umbrella in a hurricane."
]
