text = [
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Believe you can and you're halfway there.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it, believe it, build it.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The best way to predict the future is to create it.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Opportunities don’t happen, you create them.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The only place where success comes before work is in the dictionary.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "It always seems impossible until it’s done.",
    "What you do today can improve all your tomorrows.",
    "Don’t limit your challenges. Challenge your limits.",
    "The harder the battle, the sweeter the victory.",
    "Success usually comes to those who are too busy to be looking for it.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Everything you can imagine is real.",
    "You miss 100% of the shots you don’t take.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Your only limit is your mind.",
    "Act as if what you do makes a difference. It does.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Start where you are. Use what you have. Do what you can.",
    "Don’t be afraid to give up the good to go for the great.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "You don't have to be perfect. You just have to keep going.",
    "Believe in yourself and the world will be at your feet."
]
